name: Sync issue to Azure DevOps work item

"on":
  issues:
    types:
      [deleted, closed, reopened, labeled, unlabeled]

jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
      - name: Block Concurrent Executions
        uses: softprops/turnstyle@v1
        with:
          poll-interval-seconds: 30
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
    steps:
      - name: Print context
        env:
          EVENT_PAYLOAD: ${{ toJson(github.event) }}
        run: |
          echo "$EVENT_PAYLOAD"
      - uses: danhellem/github-actions-issue-to-work-item@master
        if: contains(github.event.issue.labels.*.name, env.TEST_VALUE)
        env:
          TEST_VALUE: "Type: Bug"
          ado_token: "${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}"
          github_token: "${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}"
          ado_organization: "${{ secrets.ADO_ORGANIZATION }}"
          ado_project: "${{ secrets.ADO_PROJECT }}"
          ado_area_path: "${{ secrets.ADO_AREA_PATH }}"
          ado_wit: "Bug"
          ado_new_state: "New"
          ado_close_state: "Closed"
          ado_bypassrules: true
      - uses: danhellem/github-actions-issue-to-work-item@master
        if: contains(github.event.issue.labels.*.name, env.TEST_VALUE)
        env:
          TEST_VALUE: "Type: Enhancement"
          ado_token: "${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}"
          github_token: "${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}"
          ado_organization: "${{ secrets.ADO_ORGANIZATION }}"
          ado_project: "${{ secrets.ADO_PROJECT }}"
          ado_area_path: "${{ secrets.ADO_AREA_PATH }}"
          ado_wit: "User Story"
          ado_new_state: "New"
          ado_close_state: "Closed"
          ado_bypassrules: true
